name: "✨ Feature Request"
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request 🤗
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like. A clear and concise description of what you want to happen.
      placeholder: Ex. It should be good if [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered. A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        Ex. I suggest to :
        1. Append [...]  
        2. Change [...] to [...]  
        3. Remove [...]  
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other
      description: Add any other content you want to share with us.
    validations:
      required: false
